### ISSUE TITLE
Worsermeower premium

### ISSUE THREAD

**Issue by Bloctans** [BetterMeower-Project/WorserMeower#4]
- random disconnects
- remove text filter thing
- no ads
- vulnerable to XSS

**Comment by Bloctans** [comment]
worsermeower premium is given based on if you find secret!!!!

**Comment by tnix100** [comment]
```
setInterval(cljs.send({cmd: "direct", val: {cmd: "post_home", val: "Ever wished to have a worse Meower experience? Then Worsemeower is for you! Try today at https://worse.bettermeower.app/!"}}), 300000)
```

**Comment by Bloctans** [comment]
> ```
> setInterval(cljs.send({cmd: "direct", val: {cmd: "post_home", val: "Ever wished to have a worse Meower experience? Then Worsemeower is for you! Try today at https://worse.bettermeower.app/!"}}), 300000)
> ```

why? isnt that just spam?

**Comment by JoshAtticus** [comment]
> > ```
> > setInterval(cljs.send({cmd: "direct", val: {cmd: "post_home", val: "Ever wished to have a worse Meower experience? Then Worsemeower is for you! Try today at https://worse.bettermeower.app/!"}}), 300000)
> > ```
> 
> why? isnt that just spam?

No it's genius, Albert Einstien confirmed.

**Comment by Bloctans** [comment]
im supposed to add that to worsermeower normal edition?

**Comment by JoshAtticus** [comment]
> im supposed to add that to worsermeower normal edition?

yes add it to worsermeower normal edition

**Comment by Roblox888i** [comment]
I like idea

**Comment by theycallhermax** [comment]
why

**Comment by JoshAtticus** [comment]
> I like idea

I have read your message on Reddit, although I have a few things to tell you. 

First of all, if you're saying you would stop being annoying, why are you continuously trying to engage in activities that would be annoying? 

Second of all, you've said you'd stop trying to rejoin Meower, but you still try and join through BetterMeower. We do not appreciate you abusing our service to engage in ban evasion, and do not endorse it. 

Finally, as a result of your actions, we have permanently banned you from our organisation to help prevent any further spam or potentially malicious commits.

We kindly ask you not to ever come back to Meower (or continue using BetterMeower for ban evasion), even once you turn 13, as you are not welcome on our platform.

**Comment by theycallhermax** [comment]
@Roblox888i your adjectives at a glance:

![image](https://user-images.githubusercontent.com/67456566/205536188-16f039b3-c03a-48a1-a6c9-d660f48bc053.png)

**Comment by theycallhermax** [comment]
> Finally, as a result of your actions, we have permanently banned you from our organisation to help prevent any further spam or potentially malicious commits.

besides why was roblox kid in the org in the first place?
